engines:
  scss-lint:
    enabled: true
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      selector-max:
        enabled: false
      outline-none:
        enabled: false
      order-alphabetical:
        enabled: false