engines:
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      QualifyingElement:
        enabled: false
      SpaceAfterPropertyColon:
        enabled: false
      SpaceBetweenParens:
        enabled: false
      SpaceAfterComma:
        enabled: false
      ColorVariable:
        enabled: false
      PropertySortOrder:
        enabled: false
      SingleLinePerSelector:
        enabled: false
      NameFormat:
        enabled: false
      ImportantRule:
        enabled: false
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      selector-max:
        enabled: false
      selector-max-approaching:
        enabled: false
      outline-none:
        enabled: false
      qualified-headings:
        enabled: false
      regex-selectors:
        enabled: false
      unqualified-attributes:
        enabled: false
      universal-selector:
        enabled: false
      fallback-colors:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
ratings:
  paths:
    - sass/**
    - css/**
    - "**.md"
    - "**.css"
    - "**.html"
exclude_paths:
  - docs/**