engines:
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      QualifyingElement:
        enabled: true
        allow_element_with_attribute: true
        allow_element_with_class: false
        allow_element_with_id: false
      SpaceAfterPropertyColon:
        enabled: true
        style: at_least_one_space
      SpaceBetweenParens:
        enabled: false
      SpaceAfterComma:
        enabled: true
        style: at_least_one_space
      ColorKeyword:
        enabled: false
      PropertySortOrder:
        enabled: false
      SingleLinePerSelector:
        enabled: false
      NameFormat:
        enabled: false
      ImportantRule:
        enabled: false
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      selector-max:
        enabled: false
      selector-max-approaching:
        enabled: false
      outline-none:
        enabled: false
      qualified-headings:
        enabled: false
      regex-selectors:
        enabled: false
      unqualified-attributes:
        enabled: false
      universal-selector:
        enabled: false
      fallback-colors:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
ratings:
  paths:
    - sass/**
    - css/**
    - "**.md"
    - "**.css"
    - "**.html"
exclude_paths:
  - docs/SassDoc/*