engines:
  scss-lint:
    enabled: true
    checks:
      Comment:
        enabled: false
      QualifyingElement:
        enabled: false
      SpaceAfterPropertyColon:
        enabled: false
      SpaceBetweenParens:
        enabled: false
      SpaceAfterComma:
        enabled: false
      ColorKeyword:
        enabled: false
      ColorVariable:
        enabled: false
      PropertySortOrder:
        enabled: false
      MergeableSelector:
        enabled: false
      SingleLinePerSelector:
        enabled: false
      FinalNewline:
        enabled: false
      NameFormat:
        enabled: false
      ImportantRule:
        enabled: false
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      selector-max:
        enabled: false
      selector-max-approaching:
        enabled: false
      outline-none:
        enabled: false
      order-alphabetical:
        enabled: false